=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/accessLevels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="1">
				<xs:element name="access" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="val" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="level" type="xs:integer" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="nameColor" type="xs:hexBinary" use="required" />
						<xs:attribute name="titleColor" type="xs:hexBinary" use="required" />
						<xs:attribute name="childAccess" type="xs:nonNegativeInteger" />
						<xs:attribute name="isGM" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/admin/accessLevels.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/accessLevels.xsd">
	<!-- Access levels -->
	<access level="-1" name="Banned" nameColor="FFFFFF" titleColor="FFFFFF" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="false" />
		<set name="allowTransaction" val="false" />
		<set name="allowAltG" val="false" />
		<set name="giveDamage" val="false" />
		<set name="takeAggro" val="false" />
		<set name="gainExp" val="false" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="false" />
		<set name="allowItemActionShift" val="false" />
		<set name="allowNpcActionShift" val="false" />
		<set name="allowPlayerActionShift" val="false" />
		<set name="allowStaticObjectActionShift" val="false" />
		<set name="allowSummonActionShift" val="false" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="false" />
		<set name="allowStartupInvisible" val="false" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="false" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
		<set name="allowGiveSpecialAuraSkills" val="false" />
		<set name="allowEnterAnnounce" val="false" />
	</access>
	<access level="0" name="User" nameColor="FFFFFF" titleColor="FFFFFF" childAccess="0" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="false" />
		<set name="allowTransaction" val="true" />
		<set name="allowAltG" val="false" />
		<set name="giveDamage" val="true" />
		<set name="takeAggro" val="true" />
		<set name="gainExp" val="true" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="false" />
		<set name="allowItemActionShift" val="false" />
		<set name="allowNpcActionShift" val="false" />
		<set name="allowPlayerActionShift" val="false" />
		<set name="allowStaticObjectActionShift" val="false" />
		<set name="allowSummonActionShift" val="false" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="false" />
		<set name="allowStartupInvisible" val="false" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="false" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
		<set name="allowGiveSpecialAuraSkills" val="false" />
		<set name="allowEnterAnnounce" val="false" />
	</access>
	<access level="1" name="Chat Moderator" nameColor="FFFFFF" titleColor="FFFFFF" childAccess="0" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="false" />
		<set name="allowTransaction" val="true" />
		<set name="allowAltG" val="false" />
		<set name="giveDamage" val="true" />
		<set name="takeAggro" val="true" />
		<set name="gainExp" val="true" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="false" />
		<set name="allowItemActionShift" val="false" />
		<set name="allowNpcActionShift" val="false" />
		<set name="allowPlayerActionShift" val="false" />
		<set name="allowStaticObjectActionShift" val="false" />
		<set name="allowSummonActionShift" val="false" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="false" />
		<set name="allowStartupInvisible" val="false" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="false" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
		<set name="allowGiveSpecialAuraSkills" val="false" />
		<set name="allowEnterAnnounce" val="false" />
	</access>
	<access level="2" name="Test GM" nameColor="FFFFFF" titleColor="FFFFFF" childAccess="1" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="true" />
		<set name="allowTransaction" val="false" />
		<set name="allowAltG" val="true" />
		<set name="giveDamage" val="false" />
		<set name="takeAggro" val="false" />
		<set name="gainExp" val="false" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="true" />
		<set name="allowItemActionShift" val="true" />
		<set name="allowNpcActionShift" val="true" />
		<set name="allowPlayerActionShift" val="true" />
		<set name="allowStaticObjectActionShift" val="true" />
		<set name="allowSummonActionShift" val="true" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="false" />
		<set name="allowStartupInvisible" val="false" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="false" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
		<set name="allowGiveSpecialAuraSkills" val="false" />
		<set name="allowEnterAnnounce" val="false" />
	</access>
	<access level="3" name="General GM" nameColor="0000C0" titleColor="0000C0" childAccess="2" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="true" />
		<set name="allowTransaction" val="false" />
		<set name="allowAltG" val="true" />
		<set name="giveDamage" val="false" />
		<set name="takeAggro" val="false" />
		<set name="gainExp" val="false" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="true" />
		<set name="allowItemActionShift" val="true" />
		<set name="allowNpcActionShift" val="true" />
		<set name="allowPlayerActionShift" val="true" />
		<set name="allowStaticObjectActionShift" val="true" />
		<set name="allowSummonActionShift" val="true" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="true" />
		<set name="allowStartupInvisible" val="true" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="true" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
		<set name="allowGiveSpecialAuraSkills" val="false" />
		<set name="allowEnterAnnounce" val="false" />
	</access>
	<access level="4" name="Support GM" nameColor="000C00" titleColor="000C00" childAccess="3" isGM="false">
		<set name="allowPeaceAttack" val="false" />
		<set name="allowFixedRes" val="true" />
		<set name="allowTransaction" val="false" />
		<set name="allowAltG" val="true" />
		<set name="giveDamage" val="false" />
		<set name="takeAggro" val="false" />
		<set name="gainExp" val="false" />
		<set name="gmSpeedAccess" val="false" />
		<set name="allowBalancer" val="false" />
		<set name="allowPunishment" val="false" />
		<set name="allowPunishmentChat" val="false" />
		<set name="allowDoorActionShift" val="true" />
		<set name="allowItemActionShift" val="true" />
		<set name="allowNpcActionShift" val="true" />
		<set name="allowPlayerActionShift" val="true" />
		<set name="allowStaticObjectActionShift" val="true" />
		<set name="allowSummonActionShift" val="true" />
		<set name="allowHeroAura" val="false" />
		<set name="allowStartupInvulnerable" val="true" />
		<set name="allowStartupInvisible" val="true" />
		<set name="allowStartupSilence" val="false" />
		<set name="allowStartupAutoList" val="false" />
		<set name="allowStartupDietMode" val="false" />
		<set name="allowItemRestriction" val="true" />
		<set name="allowSkillRestriction" val="true" />
		<set name="allowTradeRestrictedItems" val="false" />
		<set name="allowRestartFighting" val="true" />
		<set name="allowShowAnnouncerName" val="false" />
		<set name="allowShowCritAnnouncerName" val="false" />
		<set name="allowGiveSpecialSkills" val="false" />
