=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/clanTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="level" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="requestItems" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
												<xs:attribute name="count" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewardItems" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
												<xs:attribute name="count" type="xs:decimal" />
												<xs:attribute name="chance" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								<xs:attribute name="classId" type="xs:integer" />
								</xs:complexType>
							</xs:element>
							<xs:element name="rewardSkills" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
												<xs:attribute name="level" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								<xs:attribute name="classId" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="val" type="xs:integer" />
						<xs:attribute name="sp" type="xs:integer" />
						<xs:attribute name="members" type="xs:integer" />
						<xs:attribute name="mainPledgeLimit" type="xs:integer" />
						<xs:attribute name="academyLimit" type="xs:integer" />
						<xs:attribute name="royalsLimit" type="xs:integer" />
						<xs:attribute name="knightsLimit" type="xs:integer" />
						<xs:attribute name="haveTerritory" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/services/clanTemplates.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/clanTemplates.xsd">
	<level val="0" sp="0" mainPledgeLimit="10" />
	<level val="1" sp="20000" mainPledgeLimit="15">
		<requestItems>
			<item id="57" count="650000" /> <!-- Adena -->
		</requestItems>
	</level>
	<level val="2" sp="100000" mainPledgeLimit="20">
		<requestItems>
			<item id="57" count="2500000" /> <!-- Adena -->
		</requestItems>
	</level>
	<level val="3" sp="350000" mainPledgeLimit="30">
		<requestItems>
			<item id="1419" count="1" /> <!-- Blood Mark -->
		</requestItems>
	</level>
	<level val="4" sp="1000000" mainPledgeLimit="40">
		<requestItems>
			<item id="3874" count="1" /> <!-- Alliance Manifesto -->
		</requestItems>
	</level>
	<level val="5" sp="2500000" mainPledgeLimit="40" academyLimit="20">
		<requestItems>
			<item id="3870" count="1" /> <!-- Seal of Aspiration -->
		</requestItems>
	</level>
	<level val="6" members="30" mainPledgeLimit="40" academyLimit="20" royalsLimit="20">
		<requestItems>
			<item id="-200" count="5000" /> <!-- Clan Reputation -->
		</requestItems>
	</level>
	<level val="7" members="50" mainPledgeLimit="40" academyLimit="20" royalsLimit="20" knightsLimit="10">
		<requestItems>
			<item id="-200" count="10000" /> <!-- Clan Reputation -->
		</requestItems>
	</level>
	<level val="8" members="80" mainPledgeLimit="40" academyLimit="20" royalsLimit="20" knightsLimit="10">
		<requestItems>
			<item id="-200" count="20000" /> <!-- Clan Reputation -->
		</requestItems>
	</level>
	<level val="9" members="120" mainPledgeLimit="40" academyLimit="20" royalsLimit="20" knightsLimit="25">
		<requestItems>
			<item id="-200" count="40000" /> <!-- Clan Reputation -->
		</requestItems>
	</level>
	<level val="10" members="140" mainPledgeLimit="40" academyLimit="20" royalsLimit="20" knightsLimit="25">
		<requestItems>
			<item id="-200" count="40000" /> <!-- Clan Reputation -->
			<item id="9911" count="5" /> <!-- Blood Alliance -->
		</requestItems>
	</level>
	<level val="11" members="170" mainPledgeLimit="40" academyLimit="20" royalsLimit="30" knightsLimit="25" haveTerritory="true">
		<requestItems>
			<item id="-200" count="75000" /> <!-- Clan Reputation -->
		</requestItems>
	</level>
</list>
