=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/dimensionalRift.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rift">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="area" minOccurs="1" maxOccurs="6">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="add_parameters" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="room" minOccurs="1" maxOccurs="9">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="teleport" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="polygon" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="minX" type="xs:integer" use="required" />
												<xs:attribute name="maxX" type="xs:integer" use="required" />
												<xs:attribute name="minY" type="xs:integer" use="required" />
												<xs:attribute name="maxY" type="xs:integer" use="required" />
												<xs:attribute name="minZ" type="xs:integer" use="required" />
												<xs:attribute name="maxZ" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="spawn" minOccurs="1" maxOccurs="3">
											<xs:complexType>
												<xs:attribute name="count" type="xs:positiveInteger" use="required" />
												<xs:attribute name="delay" type="xs:positiveInteger" use="required" />
												<xs:attribute name="mobId" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="9" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="isBossRoom" use="required" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="6" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="minPlayers" type="xs:integer" />
						<xs:attribute name="hwidsLimit" type="xs:integer" />
						<xs:attribute name="ipsLimit" type="xs:integer" />
						<xs:attribute name="fragmentCount" type="xs:integer" />
						<xs:attribute name="bossRoomChance" type="xs:decimal" />
						<xs:attribute name="maxJumps" type="xs:integer" />
						<xs:attribute name="customTeleFunction" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/npcs/spawnZones/dimensionalRift.xml
<?xml version="1.0" encoding="UTF-8"?>
<rift xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/dimensionalRift.xsd">
	<!-- dimensional rift zone -->
	<area type="0">
		<!-- peace zone (waiting room) -->
		<room id="0" isBossRoom="false">
			<teleport x="-114790" y="-180576" z="-6752" />
			<polygon minX="-115440" maxX="-114160" minY="-182160" maxY="-178048" minZ="-6816" maxZ="-6240" />
		</room>
		<room id="1" isBossRoom="false">
			<teleport x="0" y="0" z="0" />
			<polygon minX="-120576" maxX="-109024" minY="-187328" maxY="-172880" minZ="-6816" maxZ="-6240" />
		</room>
	</area>
	<!-- Recruit Area -->
	<area type="1" minPlayers="2" fragmentCount="18" bossRoomChance="20" maxJumps="4" customTeleFunction="false">
		<add_parameters>
			<set name="spawnDelay" value="10000" /> <!-- time in milliseconds -->
			<set name="jumpDelayMin" value="8" /> <!-- time in minutes -->
			<set name="jumpDelayMax" value="10" /> <!-- time in minutes -->
			<set name="bossTimeModifier" value="1.5" /> <!-- room time modifier -->
		</add_parameters>
		<room id="1" isBossRoom="false">
			<teleport x="-111976" y="-182448" z="-6752" />
			<polygon minX="-112368" maxX="-111584" minY="-182832" maxY="-182064" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Soldier -->
			<spawn mobId="21659" count="2" delay="90" />
			<!-- Otherwordly Invader Archer -->
			<spawn mobId="21661" count="4" delay="80" />
			<!-- Otherwordly Invader Soldier -->
			<spawn mobId="21660" count="2" delay="90" />
		</room>
		<room id="2" isBossRoom="false">
			<teleport x="-111088" y="-182448" z="-6752" />
			<polygon minX="-111472" maxX="-110704" minY="-182832" maxY="-182064" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Priest -->
			<spawn mobId="21664" count="3" delay="90" />
			<!-- Otherwordly Invader Shaman -->
			<spawn mobId="21663" count="2" delay="90" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21662" count="3" delay="90" />
		</room>
		<room id="3" isBossRoom="false">
			<teleport x="-110296" y="-180560" z="-6752" />
			<polygon minX="-110688" maxX="-109904" minY="-180944" maxY="-180176" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Martyrs -->
			<spawn mobId="21666" count="2" delay="86" />
			<!-- Otherwordly Invader Warrior -->
			<spawn mobId="21667" count="2" delay="86" />
			<!-- Otherwordly Invader Magus -->
			<spawn mobId="21665" count="2" delay="86" />
		</room>
		<room id="4" isBossRoom="false">
			<teleport x="-109416" y="-180560" z="-6752" />
			<polygon minX="-109808" maxX="-109024" minY="-180944" maxY="-180176" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Soldier -->
			<spawn mobId="21668" count="2" delay="101" />
			<!-- Otherwordly Invader Discipline -->
			<spawn mobId="21669" count="2" delay="101" />
			<!-- Otherwordly Invader Berserker -->
			<spawn mobId="21670" count="2" delay="101" />
		</room>
		<room id="5" isBossRoom="false">
			<teleport x="-113264" y="-181520" z="-6752" />
			<polygon minX="-114032" maxX="-112496" minY="-181968" maxY="-181072" minZ="-6816" maxZ="-6240" />
			<!-- Otherwordly Invader Food -->
			<spawn mobId="18287" count="6" delay="82" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21672" count="3" delay="82" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21673" count="3" delay="82" />
		</room>
		<room id="6" isBossRoom="false">
			<teleport x="-111592" y="-180560" z="-6752" />
			<polygon minX="-112368" maxX="-110816" minY="-181008" maxY="-180112" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21675" count="4" delay="52" />
			<!-- Otherwordly Invader Warrior -->
			<spawn mobId="21676" count="4" delay="52" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21674" count="4" delay="52" />
		</room>
		<room id="7" isBossRoom="false">
			<teleport x="-109800" y="-182448" z="-6752" />
			<polygon minX="-110576" maxX="-109024" minY="-182896" maxY="-182000" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21677" count="4" delay="100" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21678" count="4" delay="100" />
			<!-- Otherwordly Invader Food -->
			<spawn mobId="18288" count="4" delay="100" />
		</room>
		<room id="8" isBossRoom="false">
			<teleport x="-111592" y="-181520" z="-6752" />
			<polygon minX="-112368" maxX="-110816" minY="-181968" maxY="-181072" minZ="-6816" maxZ="-6240" />
			<!-- Otherworldy Invader Elite Soldier -->
			<spawn mobId="21679" count="4" delay="137" />
			<!-- Otherwordly Invader Magus -->
			<spawn mobId="21681" count="4" delay="137" />
			<!-- Otherwordly Invader Elite Soldier -->
			<spawn mobId="21680" count="4" delay="137" />
		</room>
		<room id="9" isBossRoom="true">
			<teleport x="-109912" y="-181520" z="-6752" />
			<polygon minX="-110688" maxX="-109136" minY="-181968" maxY="-181072" minZ="-6816" maxZ="-6240" />
			<!-- Anakazel -->
			<spawn mobId="25333" count="1" delay="600" />
		</room>
	</area>
	<!-- Soldier Area -->
	<area type="2" minPlayers="2" fragmentCount="21" bossRoomChance="20" maxJumps="4" customTeleFunction="false">
		<add_parameters>
			<set name="spawnDelay" value="10000" /> <!-- time in milliseconds -->
			<set name="jumpDelayMin" value="8" /> <!-- time in minutes -->
			<set name="jumpDelayMax" value="10" /> <!-- time in minutes -->
			<set name="bossTimeModifier" value="1.5" /> <!-- room time modifier -->
		</add_parameters>
		<room id="1" isBossRoom="false">
			<teleport x="-111976" y="-179624" z="-6752" />
			<polygon minX="-112368" maxX="-111584" minY="-180016" maxY="-179232" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21682" count="2" delay="90" />
			<!-- Dimension Invader Archer -->
			<spawn mobId="21684" count="4" delay="80" />
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21683" count="2" delay="90" />
		</room>
		<room id="2" isBossRoom="false">
			<teleport x="-111088" y="-179624" z="-6752" />
			<polygon minX="-111472" maxX="-110704" minY="-180016" maxY="-179232" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Priest -->
			<spawn mobId="21687" count="3" delay="90" />
			<!-- Dimension Invader Shaman -->
			<spawn mobId="21686" count="2" delay="90" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21685" count="3" delay="90" />
		</room>
		<room id="3" isBossRoom="false">
			<teleport x="-110296" y="-177744" z="-6752" />
			<polygon minX="-110688" maxX="-109904" minY="-178128" maxY="-177360" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Martyrs -->
			<spawn mobId="21689" count="2" delay="86" />
			<!-- Dimension Invader Warrior -->
			<spawn mobId="21690" count="2" delay="86" />
			<!-- Dimension Invader Magus -->
			<spawn mobId="21688" count="2" delay="86" />
		</room>
		<room id="4" isBossRoom="false">
			<teleport x="-109416" y="-177744" z="-6752" />
			<polygon minX="-109808" maxX="-109024" minY="-178128" maxY="-177360" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Soldier -->
			<spawn mobId="21691" count="2" delay="101" />
			<!-- Dimension Invader Discipline -->
			<spawn mobId="21692" count="2" delay="101" />
			<!-- Dimension Invader Berserker -->
			<spawn mobId="21693" count="2" delay="101" />
		</room>
		<room id="5" isBossRoom="false">
			<teleport x="-113264" y="-178688" z="-6752" />
			<polygon minX="-114032" maxX="-112496" minY="-179136" maxY="-178240" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Food -->
			<spawn mobId="18289" count="6" delay="82" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21695" count="3" delay="82" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21696" count="3" delay="82" />
		</room>
		<room id="6" isBossRoom="false">
			<teleport x="-111592" y="-177744" z="-6752" />
			<polygon minX="-112368" maxX="-110816" minY="-178192" maxY="-177296" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21698" count="4" delay="52" />
			<!-- Dimension Invader Warrior -->
			<spawn mobId="21699" count="4" delay="52" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21697" count="4" delay="52" />
		</room>
		<room id="7" isBossRoom="false">
			<teleport x="-109800" y="-179624" z="-6752" />
			<polygon minX="-110576" maxX="-109024" minY="-180064" maxY="-179168" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21700" count="4" delay="100" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21701" count="4" delay="100" />
			<!-- Dimension Invader Food -->
			<spawn mobId="18290" count="4" delay="100" />
		</room>
		<room id="8" isBossRoom="false">
			<teleport x="-111592" y="-178688" z="-6752" />
			<polygon minX="-112368" maxX="-110816" minY="-179136" maxY="-178240" minZ="-6816" maxZ="-6240" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21702" count="4" delay="137" />
			<!-- Dimension Invader Magus -->
			<spawn mobId="21704" count="4" delay="137" />
			<!-- Dimension Invader Elite Soldier -->
			<spawn mobId="21703" count="4" delay="137" />
		</room>
		<room id="9" isBossRoom="true">
			<teleport x="-109912" y="-178688" z="-6752" />
			<polygon minX="-110688" maxX="-109136" minY="-179136" maxY="-178240" minZ="-6816" maxZ="-6240" />
			<!-- Anakazel -->
			<spawn mobId="25334" count="1" delay="600" />
		</room>
	</area>
	<!-- Officer Area -->
	<area type="3" minPlayers="2" fragmentCount="24" bossRoomChance="20" maxJumps="4" customTeleFunction="false">
		<add_parameters>
			<set name="spawnDelay" value="10000" /> <!-- time in milliseconds -->
			<set name="jumpDelayMin" value="8" /> <!-- time in minutes -->
			<set name="jumpDelayMax" value="10" /> <!-- time in minutes -->
			<set name="bossTimeModifier" value="1.5" /> <!-- room time modifier -->
		</add_parameters>
