=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/dressWeapon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="weapon" maxOccurs="9999" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="price" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required" type="xs:int" />
									<xs:attribute name="count" use="required" type="xs:int" />
								</xs:complexType>
							</xs:element>
							<xs:element name="removed" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="modifier" use="required" type="xs:decimal" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="id" use="required" type="xs:int" />
									<xs:attribute name="level" use="required" type="xs:int" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required" type="xs:int" />
						<xs:attribute name="nameEn" use="required" type="xs:normalizedString" />
						<xs:attribute name="nameRu" type="xs:normalizedString" />
						<xs:attribute name="type" use="required" type="xs:normalizedString" />
						<xs:attribute name="allowEnchant" type="xs:boolean" />
						<xs:attribute name="allowAugment" type="xs:boolean" />
						<xs:attribute name="isForSell" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/services/dress/dressWeapon.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/dressWeapon.xsd">
	<weapon id="6611" nameEn="Infinity Blade" type="Sword" allowEnchant="false" allowAugment="false">
		<price id="4037" count="50" />
	</weapon>
	<weapon id="6620" nameEn="Infinity Wing" type="Dual Sword" allowEnchant="false" allowAugment="false">
		<price id="4037" count="50" />
	</weapon>
	<weapon id="23100" nameEn="Insane Dagger" type="Dagger">
		<price id="4037" count="50" />
	</weapon>
	<weapon id="23101" nameEn="Insane Dual Daggers" type="Dual Dagger">
		<price id="4037" count="50" />
	</weapon>
	 <weapon id="23102" nameEn="Insane Bow" type="Bow">
		<price id="4037" count="50" />
	</weapon>
	 <weapon id="23103" nameEn="Insane Shooter" type="Crossbow">
		<price id="4037" count="50" />
	</weapon>
	 <weapon id="8206" nameEn="Heretic Priest Sword" type="Dual Dagger">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="8689" nameEn="Akamanah Duals" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="8190" nameEn="Zariche Sword" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15688" nameEn="Triumph Ancientsword" type="Ancient">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15676" nameEn="Triumph Blade" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15686" nameEn="Triumph Bow" type="Bow">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15689" nameEn="Triumph Crossbow" type="Crossbow">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15679" nameEn="Triumph Crusher" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15677" nameEn="Triumph Dagger" type="Dagger">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15678" nameEn="Triumph Hammer" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15681" nameEn="Triumph Jamadhr" type="Dual Fist">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15685" nameEn="Triumph Magic Sword" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15687" nameEn="Triumph Rapier" type="Rapier">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15682" nameEn="Triumph Spear" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15683" nameEn="Triumph Staff" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15684" nameEn="Triumph Two Hand Staff" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="15680" nameEn="Triumph Two Hand Sword" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="8205" nameEn="Heretic Priest Sigil" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="21959" nameEn="Blood Brother" type="Ancient">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="78" nameEn="Great Sword" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="79" nameEn="Sword of Damascus" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="80" nameEn="Tallum Blade" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="81" nameEn="Dragon Slayer" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="82" nameEn="God's Blade" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="85" nameEn="Phantom Sword" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="91" nameEn="Heavy War Axe" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="92" nameEn="Sprite's Staff" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="97" nameEn="Lance" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="98" nameEn="Halberd" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="142" nameEn="Keshanberk" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="146" nameEn="Ghoulbane" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="147" nameEn="Tear of Darkness" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="148" nameEn="Sword of Valhalla" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="149" nameEn="Sword of Life" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="150" nameEn="Elemental Sword" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="151" nameEn="Sword of Miracles" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="164" nameEn="Elysian" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="165" nameEn="Yablonski's Hammer" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="175" nameEn="Art of Battle Axe" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10004" nameEn="Dynasty Dual Sword" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10215" nameEn="Icarus Sawsword" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10216" nameEn="Icarus Disperser" type="Dagger">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10217" nameEn="Icarus Spirit" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10218" nameEn="Icarus Heavy Arms" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10219" nameEn="Icarus Trident" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10220" nameEn="Icarus Hammer" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10221" nameEn="Icarus Hand" type="Dual Fist">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10222" nameEn="Icarus Hall" type="Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10223" nameEn="Icarus Spitter" type="Bow">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10224" nameEn="Icarus Stinger" type="Rapier">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10225" nameEn="Icarus Wingblade" type="Ancient">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10226" nameEn="Icarus Shooter" type="Crossbow">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10252" nameEn="Dynasty Staff" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10253" nameEn="Dynasty Crusher" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10415" nameEn="Icarus Dual Sword" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10870" nameEn="Great Sword - Lightning" type="Big Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10874" nameEn="Great Axe - Thunder" type="Pole">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10878" nameEn="Sword of Limit*Sword of Limit - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10879" nameEn="Sword of Limit*Sword of Delusion - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10880" nameEn="Sword of Limit*Sword of Nightmare - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10881" nameEn="Sword of Limit*Tsurugi - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10882" nameEn="Innominate Victory - Lightning" type="Ancient">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10886" nameEn="Dark Elven Long Bow - Concentration" type="Bow">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10890" nameEn="Sword of Delusion*Sword of Delusion - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10891" nameEn="Sword of Delusion*Sword of Nightmare - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10892" nameEn="Sword of Delusion*Tsurugi - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10893" nameEn="Sword of Valhalla - Nature" type="Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10897" nameEn="Stormbringer*Samurai Long Sword - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10902" nameEn="Arthro Nail - Destruction" type="Dual Fist">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10906" nameEn="Ice Storm Hammer - Lightning" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10910" nameEn="Sword of Nightmare*Sword of Nightmare - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10911" nameEn="Sword of Nightmare*Tsurugi - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10912" nameEn="Military Fleuret - Destruction" type="Rapier">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10916" nameEn="Sprite's Staff - Hail" type="Big Blunt">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10920" nameEn="Tsurugi*Tsurugi - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10921" nameEn="Caliburs*Sword of Limit - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10922" nameEn="Caliburs*Sword of Delusion - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10923" nameEn="Caliburs*Sword of Nightmare - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10924" nameEn="Caliburs*Tsurugi - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10925" nameEn="Caliburs*Caliburs - Destruction" type="Dual Sword">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10926" nameEn="Kris - Confusion" type="Dagger">
		<price id="4037" count="500" />
	</weapon>
	<weapon id="10930" nameEn="Keshanberk - Destruction" type="Sword">
		<price id="4037" count="500" />
