=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/fight_events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="event" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="value" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="eventItems" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="class" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="itemList" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence minOccurs="0" maxOccurs="unbounded">
																<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:positiveInteger" />
																		<xs:attribute name="amount" type="xs:positiveInteger" />
																		<xs:attribute name="enchant" type="xs:integer" />
																		<xs:attribute name="augmentation" type="xs:string" />
																		<xs:attribute name="elementals" type="xs:string" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="team" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
						<xs:attribute name="nameEn" type="xs:string" />
						<xs:attribute name="nameRu" type="xs:string" />
						<xs:attribute name="impl" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/[06] Korean Style.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fight_events.xsd">
	<event id="6" nameEn="Korean Style" nameRu="Корейский Стиль" impl="KoreanStyle">
		<parameter name="icon" value="Icon.skill5074" />
		<parameter name="descEn" value="You will need to defeat enemy Team in 1 VS 1 Fights!" />
		<parameter name="descRu" value="Вам нужно будет победить вражескую команду в боях 1 на 1!" />
		<parameter name="roundRunTime" value="-1" />
		<parameter name="roundEvent" value="false" />
		<parameter name="isAutoTimed" value="true" />
		<parameter name="autoTimes" value="0 5,17 * * *" />
		<parameter name="teamed" value="true" />
		<parameter name="canTargetTeam" value="false" />
		<parameter name="useBuffs" value="false" />
		<parameter name="dispelBuffs" value="true" />
		<parameter name="givePvpPoints" value="false" />
		<parameter name="canUseScrolls" value="false" />
		<parameter name="canUsePotions" value="false" />
		<parameter name="canItemSummons" value="false" />
		<parameter name="canUseCommunity" value="true" /> <!-- if false will block buffer and other community services -->
		<parameter name="rootBetweenRounds" value="true" />
		<parameter name="loseBuffsOnDeath" value="false" />
		<parameter name="excludedClasses" value="HEALERS" />
		<parameter name="excludedSkills" value="1410;438;21090;23118" /> <!-- Salvation-type skills -->
		<parameter name="validLevels" value="75-85" /> <!-- Valid levels diff -->
		<parameter name="validProffs" value="2;3" /> <!-- Valid proffs levels list -->
		<parameter name="respawnTime" value="-1" />
		<parameter name="ressAllowed" value="false" />
		<parameter name="winnerByDamage" value="true" /> <!-- duel winner if players survived -->
		<!-- better to make different rewards for different positions -->
		<!-- can use several items in one position -->
		<parameter name="rewardByParticipation" value="57,100000" />
		<parameter name="rewardByKillPlayer" value="4037,1" />
		<parameter name="rewardByWinner" value="4037,6" />
		<parameter name="rewardByTopKiller" value="4037,3" />
		<parameter name="instanced" value="true" />
		<parameter name="isUseEventItems" value="false" />
		<!-- check and unequip items from slot numbers -->
		<parameter name="checkItemSlots" value="23;0;8;9;4;13;14;1;5;7;10;6;11;12;2;3;17;18;19;20;21;16;15;24" />
		<!-- Example event items by classes -->
		<eventItems>
			<class id="106"> <!-- Shillien Templar -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
			<class id="90"> <!-- Phoenix Knight -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
		</eventItems>
 	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/[10] Monster Attack.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fight_events.xsd">
	<event id="10" nameEn="Monster Attack" nameRu="Атака Монстров" impl="MonsterAttack">
		<parameter name="icon" value="L2UI_CT1.clan_DF_TerritoryWarIcon_Aden" />
        	<parameter name="descEn" value="Hold back the monsters attack on town and not to die defender!" />
        	<parameter name="descRu" value="Сдерживайте нападение монстров на город и защитите стража!" />
		<parameter name="roundRunTime" value="20" />
        	<parameter name="roundEvent" value="false" />
		<parameter name="isAutoTimed" value="true" />
		<parameter name="autoTimes" value="0 9,21 * * *" />
		<parameter name="teamed" value="false" />
		<parameter name="canAttackPlayers" value="false" />
		<parameter name="useBuffs" value="true" />
		<parameter name="dispelBuffs" value="true" />
		<parameter name="fighterBuffs" value="1204,2;1086,2;1068,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="mageBuffs" value="1204,2;1085,3;1059,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="givePvpPoints" value="false" />
		<parameter name="canUseScrolls" value="false" />
		<parameter name="canUsePotions" value="false" />
		<parameter name="canItemSummons" value="false" />
		<parameter name="canUseCommunity" value="true" /> <!-- if false will block buffer and other community services -->
		<parameter name="rootBetweenRounds" value="true" />
		<parameter name="loseBuffsOnDeath" value="false" />
		<parameter name="excludedClasses" value="" />
		<parameter name="validLevels" value="75-85" /> <!-- Valid levels diff -->
		<parameter name="validProffs" value="2;3" /> <!-- Valid proffs levels list -->
		<parameter name="respawnTime" value="0" />
		<parameter name="ressAllowed" value="true" />
		<parameter name="mobsInWaveCount" value="15;30;45" />
		<parameter name="wavesInterval" value="30;180;300" />
		<parameter name="monstersId" value="53007;53008;53009;53010;53011;53012;53013;53014" />
		<!-- better to make different rewards for different positions -->
		<!-- can use several items in one position -->
		<parameter name="rewardByParticipation" value="57,100000" />
		<parameter name="rewardByKillPlayer" value="4037,1" /> <!-- reward for mob killing -->
		<parameter name="instanced" value="true" />
		<parameter name="isUseEventItems" value="false" />
		<!-- check and unequip items from slot numbers -->
		<parameter name="checkItemSlots" value="23;0;8;9;4;13;14;1;5;7;10;6;11;12;2;3;17;18;19;20;21;16;15;24" />
		<!-- Example event items by classes -->
		<eventItems>
			<class id="106"> <!-- Shillien Templar -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
			<class id="90"> <!-- Phoenix Knight -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
		</eventItems>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/[04] Capture The Flag.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fight_events.xsd">
	<event id="4" nameEn="Capture The Flag" nameRu="Захват Флага" impl="CaptureTheFlag">
		<parameter name="icon" value="Icon.etc_bloodpledge_point_i00" />
		<parameter name="descEn" value="You need to steal the flag from your opponents and bring it to your territory!" />
		<parameter name="descRu" value="Необходимо украсть флаг у противников и принести его на свою территорию!" />
		<parameter name="roundRunTime" value="10" />
		<parameter name="roundEvent" value="false" />
		<parameter name="isAutoTimed" value="true" />
		<parameter name="autoTimes" value="0 3,15 * * *" />
		<parameter name="teamed" value="true" />
		<parameter name="canTargetTeam" value="false" />
		<parameter name="useBuffs" value="false" />
		<parameter name="dispelBuffs" value="true" />
		<parameter name="fighterBuffs" value="1204,2;1086,2;1068,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="mageBuffs" value="1204,2;1085,3;1059,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="givePvpPoints" value="false" />
		<parameter name="canUseScrolls" value="false" />
		<parameter name="canUsePotions" value="false" />
		<parameter name="canItemSummons" value="false" />
		<parameter name="canUseCommunity" value="true" /> <!-- if false will block buffer and other community services -->
		<parameter name="rootBetweenRounds" value="true" />
		<parameter name="loseBuffsOnDeath" value="false" />
		<parameter name="excludedClasses" value="" />
		<parameter name="excludedSkills" value="922" />
		<parameter name="validLevels" value="75-85" /> <!-- Valid levels diff -->
		<parameter name="validProffs" value="2;3" /> <!-- Valid proffs levels list -->
		<parameter name="respawnTime" value="5" />
		<parameter name="ressAllowed" value="false" />
		<!-- better to make different rewards for different positions -->
		<!-- can use several items in one position -->
		<parameter name="rewardByParticipation" value="57,100000" />
		<parameter name="rewardByCaptureFlag" value="4037,1" />
		<parameter name="rewardByWinner" value="4037,6" />
		<parameter name="rewardByTopKiller" value="4037,3" />
		<parameter name="rewardByCaptureFlagAlone" value="false" /> <!-- if enable reward for flag is given to one who brought it -->
		<parameter name="captureFlagLimit" value="-1" /> <!-- total flags after which event will end -->
		<parameter name="instanced" value="true" />
		<parameter name="isUseEventItems" value="false" />
		<!-- check and unequip items from slot numbers -->
		<parameter name="checkItemSlots" value="23;0;8;9;4;13;14;1;5;7;10;6;11;12;2;3;17;18;19;20;21;16;15;24" />
		<!-- Example event items by classes -->
		<eventItems>
			<class id="106"> <!-- Shillien Templar -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
			<class id="90"> <!-- Phoenix Knight -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
		</eventItems>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/[07] Team vs Team Round.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fight_events.xsd">
	<event id="7" nameEn="Team VS Team Round" nameRu="Раундная Командная Битва" impl="TeamVSTeamRound">
		<parameter name="icon" value="L2UI_CT1.clan_DF_TerritoryWarIcon_Oren" />
		<parameter name="descEn" value="Kill all players of the enemy team. The event lasts 3 rounds!" />
		<parameter name="descRu" value="Убить всех игроков вражеской команды. Ивент длится 3 раунда!" />
		<parameter name="roundRunTime" value="-1" />
		<parameter name="roundEvent" value="true" />
		<parameter name="rounds" value="3" />
		<parameter name="isAutoTimed" value="true" />
		<parameter name="autoTimes" value="0 6,18 * * *" />
		<parameter name="teamed" value="true" />
		<parameter name="canTargetTeam" value="false" />
		<parameter name="useBuffs" value="true" />
		<parameter name="dispelBuffs" value="true" />
		<parameter name="fighterBuffs" value="1204,2;1086,2;1068,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="mageBuffs" value="1204,2;1085,3;1059,3;1045,6;1048,6;1040,3;1062,2;1036,2" />
		<parameter name="givePvpPoints" value="false" />
		<parameter name="canUseScrolls" value="false" />
		<parameter name="canUsePotions" value="false" />
		<parameter name="canItemSummons" value="false" />
		<parameter name="canUseCommunity" value="true" /> <!-- if false will block buffer and other community services -->
		<parameter name="rootBetweenRounds" value="true" />
		<parameter name="loseBuffsOnDeath" value="false" />
		<parameter name="excludedClasses" value="" />
		<parameter name="validLevels" value="75-85" /> <!-- Valid levels diff -->
		<parameter name="validProffs" value="2;3" /> <!-- Valid proffs levels list -->
		<parameter name="respawnTime" value="-1" />
		<parameter name="ressAllowed" value="false" />
		<!-- better to make different rewards for different positions -->
		<!-- can use several items in one position -->
		<parameter name="rewardByParticipation" value="57,100000" />
		<parameter name="rewardByWinner" value="4037,6" />
		<parameter name="rewardByTopKiller" value="4037,3" />
		<parameter name="instanced" value="true" />
		<parameter name="isUseEventItems" value="false" />
		<!-- check and unequip items from slot numbers -->
		<parameter name="checkItemSlots" value="23;0;8;9;4;13;14;1;5;7;10;6;11;12;2;3;17;18;19;20;21;16;15;24" />
		<!-- Example event items by classes -->
		<eventItems>
			<class id="106"> <!-- Shillien Templar -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
			<class id="90"> <!-- Phoenix Knight -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
		</eventItems>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/[05] Treasure Hunt.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fight_events.xsd">
	<event id="5" nameEn="Treasure Hunt" nameRu="Поиск Сокровищ" impl="FFATreasureHunt">
		<parameter name="icon" value="Icon.event_hero_treasure_box_i00" />
		<parameter name="descEn" value="Need find chests and open them. Points are also given for killing players!" />
		<parameter name="descRu" value="Необходимо найти и открыть сундуки. Также даются очки за убийство игроков!" />
		<parameter name="roundRunTime" value="10" />
		<parameter name="isAutoTimed" value="true" />
		<parameter name="autoTimes" value="0 4,16 * * *" />
		<parameter name="roundEvent" value="false" />
		<parameter name="teamed" value="false" />
		<parameter name="useBuffs" value="false" />
		<parameter name="dispelBuffs" value="true" />
		<parameter name="givePvpPoints" value="false" />
		<parameter name="canUseScrolls" value="false" />
		<parameter name="canUsePotions" value="false" />
		<parameter name="canItemSummons" value="false" />
		<parameter name="canUseCommunity" value="true" /> <!-- if false will block buffer and other community services -->
		<parameter name="rootBetweenRounds" value="true" />
		<parameter name="loseBuffsOnDeath" value="false" />
		<parameter name="excludedClasses" value="HEALERS" />
		<parameter name="validLevels" value="75-85" /> <!-- Valid levels diff -->
		<parameter name="validProffs" value="2;3" /> <!-- Valid proffs levels list -->
		<parameter name="respawnTime" value="5" />
		<parameter name="ressAllowed" value="false" />
		<!-- better to make different rewards for different positions -->
		<!-- can use several items in one position -->
		<parameter name="rewardByParticipation" value="57,100000" />
		<parameter name="rewardByKillPlayer" value="4037,1" />
		<parameter name="rewardByTopKiller" value="4037,5" />
		<parameter name="rewardByOpenChest" value="4037,1" />
		<parameter name="scoreForChest" value="1" /> <!-- need for calc rewardByWinner param if use -->
		<parameter name="scoreForKilledPlayer" value="0" /> <!-- need for calc rewardByWinner param if use -->
		<parameter name="numberOfChests" value="7" />
		<parameter name="timeForRespawningChest" value="15" />
		<parameter name="instanced" value="true" />
		<parameter name="isUseEventItems" value="false" />
		<!-- check and unequip items from slot numbers -->
		<parameter name="checkItemSlots" value="23;0;8;9;4;13;14;1;5;7;10;6;11;12;2;3;17;18;19;20;21;16;15;24" />
		<!-- Example event items by classes -->
		<eventItems>
			<class id="106"> <!-- Shillien Templar -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
			<class id="90"> <!-- Phoenix Knight -->
				<itemList>
					<item id="14120" amount="1" enchant="16" augmentation="16340:13400" elementals="0:300" /> <!-- Vesper Cutter -->
					<item id="13435" amount="1" /> <!-- Vesper Noble Breastplate -->
					<item id="13448" amount="1" /> <!-- Vesper Noble Gaiters -->
					<item id="13140" amount="1" /> <!-- Vesper Noble Helmet -->
                			<item id="13450" amount="1" /> <!-- Vesper Noble Boots -->
               				<item id="13449" amount="1" /> <!-- Vesper Noble Gauntlet -->
                			<item id="13471" amount="1" /> <!-- Vesper Shield -->
                			<item id="14164" amount="1" /> <!-- Vesper Necklace -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="16376" amount="1" /> <!-- Vesper Earring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
					<item id="14165" amount="1" /> <!-- Vesper Ring -->
				</itemList>
			</class>
		</eventItems>
	</event>
</list>
