=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/herbSpawnZones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="param" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="chance" type="xs:positiveInteger" use="required" />
						<xs:attribute name="rndAmount" type="xs:positiveInteger" use="required" />
						<xs:attribute name="respawnDelay" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="location" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="val" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/npcs/spawnZones/herbSpawnZones.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/herbSpawnZones.xsd">
	<!-- chance spawn | random amount at location | recycle spawn -->
	<param chance="100" rndAmount="3" respawnDelay="60" />
	<!-- x y z range -->
	<location val="90891 171809 -3765 850" />
	<location val="91038 173332 -3765 850" />
	<location val="84825 175500 -3765 850" />
	<location val="84604 180407 -3760 850" />
	<location val="83144 181263 -3765 850" />
	<location val="79535 181557 -3760 850" />
	<location val="79700 183108 -3765 850" />
	<location val="82782 185375 -3760 850" />
	<location val="82450 186523 -3765 850" />
	<location val="79497 187199 -3760 850" />
	<location val="80337 188781 -3765 850" />
	<location val="83265 189267 -3765 850" />
	<location val="86443 186673 -3765 850" />
	<location val="86104 185645 -3760 850" />
	<location val="87907 183527 -3760 850" />
	<location val="87158 186115 -3760 850" />
	<location val="89498 187474 -3760 850" />
	<location val="91829 188645 -3760 850" />
	<location val="93125 191117 -3765 850" />
	<location val="90760 192797 -3765 850" />
	<location val="87554 191466 -3765 850" />
	<location val="86224 192764 -3765 850" />
	<location val="83764 193413 -3768 850" />
	<location val="80968 192765 -3764 850" />
	<location val="79371 191145 -3760 850" />
	<location val="81721 191475 -3760 850" />
	<location val="88809 204734 -3760 850" />
	<location val="89814 203520 -3760 850" />
	<location val="91576 204594 -3760 850" />
	<location val="91232 205447 -3765 850" />
	<location val="93641 208728 -3765 850" />
	<location val="94620 206690 -3765 850" />
	<location val="94351 211663 -3765 850" />
	<location val="90628 211426 -3760 850" />
	<location val="89913 212538 -3765 850" />
	<location val="91453 214318 -3760 850" />
	<location val="92696 216789 -3760 850" />
	<location val="91934 219138 -3765 850" />
	<location val="92528 220140 -3760 850" />
	<location val="92756 223352 -3765 850" />
	<location val="91200 223511 -3765 850" />
	<location val="91049 224798 -3760 850" />
	<location val="87657 225484 -3760 850" />
	<location val="86296 226629 -3760 850" />
	<location val="84900 226958 -3765 850" />
	<location val="83944 224498 -3760 850" />
	<location val="86631 223720 -3760 850" />
	<location val="87988 222801 -3760 850" />
	<location val="82490 221379 -3760 850" />
	<location val="80914 221359 -3765 850" />
	<location val="80731 218907 -3760 850" />
	<location val="77147 217591 -3760 850" />
	<location val="77193 214720 -3765 850" />
	<location val="76947 213449 -3760 850" />
	<location val="80313 210834 -3760 850" />
	<location val="78887 210534 -3765 850" />
	<location val="82902 209212 -3765 850" />
	<location val="84569 206135 -3760 850" />
	<location val="85326 215156 -3765 850" />
	<location val="89050 218827 -3765 850" />
	<location val="88405 217174 -3760 850" />
	<location val="87750 210575 -3765 850" />
</list>
