=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/initialBuff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="2">
				<xs:element name="newbieBuff" minOccurs="1" maxOccurs="136">
					<xs:complexType>
						<xs:attribute name="activated" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="class" minOccurs="1" maxOccurs="136">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="buff" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="lvl" type="xs:positiveInteger" />
									<xs:attribute name="time" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="classId">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="136" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/chars/initialBuff.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/initialBuff.xsd">
	<!--
	########## Create char params for buffs ##########
	id   - separate buff id players. Example format [id="1323"]
	lvl   - separate buff level players. Example format [lvl="315"] if remove value, take maxLvl skill
	time     - separate buff time in minutes. Example format [time="10"] if -1 disable, take default duration
	-->
	<newbieBuff activated="false"/>
	<!-- Human Fighter -->
	<class classId="0">
		<buff id="1062" /> <!-- Bersercer Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="4699" /> <!-- Blessing of Queen -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1363" /> <!-- Chant of Victory -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="825" /> <!-- Sharp Edge -->
		<buff id="828" /> <!-- Case Harden -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1388" /> <!-- Greater Might -->
		<buff id="1519" /> <!-- Chant of Blood Awakening -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="271" /> <!-- Dance of the Warrior -->
		<buff id="274" /> <!-- Dance of Fire -->
		<buff id="275" /> <!-- Dance of Fury -->
		<buff id="310" /> <!-- Dance of the Vampire -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="269" /> <!-- Song of Hunter -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="364" /> <!-- Song of Champion -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
	</class>
	<!-- Human Mystic -->
	<class classId="10">
		<buff id="1085" /> <!-- Acumen -->
		<buff id="830" /> <!-- Embroider -->
		<buff id="1062" /> <!-- Berserker Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1078" /> <!-- Concentration -->
		<buff id="1303" /> <!-- Wild Magic -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1307" /> <!-- Prayer -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1389" /> <!-- Greater Shield -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="1357" /> <!-- Prophecy of Wind -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="363" /> <!-- Song of Meditation -->
		<buff id="273" /> <!-- Dance of the Mystic -->
		<buff id="276" /> <!-- Dance of Concentration -->
		<buff id="365" /> <!-- Siren's Dance -->
	</class>
	<!-- Elven Fighter -->
	<class classId="18">
		<buff id="1062" /> <!-- Bersercer Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="4699" /> <!-- Blessing of Queen -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1363" /> <!-- Chant of Victory -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="825" /> <!-- Sharp Edge -->
		<buff id="828" /> <!-- Case Harden -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1388" /> <!-- Greater Might -->
		<buff id="1519" /> <!-- Chant of Blood Awakening -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="271" /> <!-- Dance of the Warrior -->
		<buff id="274" /> <!-- Dance of Fire -->
		<buff id="275" /> <!-- Dance of Fury -->
		<buff id="310" /> <!-- Dance of the Vampire -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="269" /> <!-- Song of Hunter -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="364" /> <!-- Song of Champion -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
	</class>
	<!-- Elven Mystic -->
	<class classId="25">
		<buff id="1085" /> <!-- Acumen -->
		<buff id="830" /> <!-- Embroider -->
		<buff id="1062" /> <!-- Berserker Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1078" /> <!-- Concentration -->
		<buff id="1303" /> <!-- Wild Magic -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1307" /> <!-- Prayer -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1389" /> <!-- Greater Shield -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="1357" /> <!-- Prophecy of Wind -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="363" /> <!-- Song of Meditation -->
		<buff id="273" /> <!-- Dance of the Mystic -->
		<buff id="276" /> <!-- Dance of Concentration -->
		<buff id="365" /> <!-- Siren's Dance -->
	</class>
	<!-- Dark Fighter -->
	<class classId="31">
		<buff id="1062" /> <!-- Bersercer Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="4699" /> <!-- Blessing of Queen -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1363" /> <!-- Chant of Victory -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="825" /> <!-- Sharp Edge -->
		<buff id="828" /> <!-- Case Harden -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1388" /> <!-- Greater Might -->
		<buff id="1519" /> <!-- Chant of Blood Awakening -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="271" /> <!-- Dance of the Warrior -->
		<buff id="274" /> <!-- Dance of Fire -->
		<buff id="275" /> <!-- Dance of Fury -->
		<buff id="310" /> <!-- Dance of the Vampire -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="269" /> <!-- Song of Hunter -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="364" /> <!-- Song of Champion -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
	</class>
	<!-- Dark Mystic -->
	<class classId="38">
		<buff id="1085" /> <!-- Acumen -->
		<buff id="830" /> <!-- Embroider -->
		<buff id="1062" /> <!-- Berserker Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1078" /> <!-- Concentration -->
		<buff id="1303" /> <!-- Wild Magic -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1307" /> <!-- Prayer -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1389" /> <!-- Greater Shield -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="1357" /> <!-- Prophecy of Wind -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="304" /> <!-- Song of Vitality -->
		<buff id="349" /> <!-- Song of Renewal -->
		<buff id="363" /> <!-- Song of Meditation -->
		<buff id="273" /> <!-- Dance of the Mystic -->
		<buff id="276" /> <!-- Dance of Concentration -->
		<buff id="365" /> <!-- Siren's Dance -->
	</class>
	<!-- Orc Fighter -->
	<class classId="44">
		<buff id="1062" /> <!-- Bersercer Spirit -->
		<buff id="1035" /> <!-- Mental Shield -->
		<buff id="1259" /> <!-- Resist Shock -->
		<buff id="4699" /> <!-- Blessing of Queen -->
		<buff id="4703" /> <!-- Gift of Seraphim -->
		<buff id="1363" /> <!-- Chant of Victory -->
		<buff id="1323" /> <!-- Noblesse Blessing -->
		<buff id="825" /> <!-- Sharp Edge -->
		<buff id="828" /> <!-- Case Harden -->
		<buff id="1461" /> <!-- Chant of Protection -->
		<buff id="1388" /> <!-- Greater Might -->
		<buff id="1519" /> <!-- Chant of Blood Awakening -->
		<buff id="1501" /> <!-- Counter Critical -->
		<buff id="1232" /> <!-- Blazing Skin -->
		<buff id="1397" /> <!-- Clarity -->
		<buff id="1354" /> <!-- Arcane Protection -->
		<buff id="1353" /> <!-- Divine Protection -->
		<buff id="1352" /> <!-- Elemental Protection -->
		<buff id="271" /> <!-- Dance of the Warrior -->
		<buff id="274" /> <!-- Dance of Fire -->
		<buff id="275" /> <!-- Dance of Fury -->
		<buff id="310" /> <!-- Dance of the Vampire -->
		<buff id="264" /> <!-- Song of Earth -->
		<buff id="267" /> <!-- Song of Warding -->
		<buff id="268" /> <!-- Song of Wind -->
		<buff id="269" /> <!-- Song of Hunter -->
