=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/lifestone_map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="configs" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lifeStones" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="grade" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:int" use="required" />
									<xs:attribute name="skillChance" type="xs:int" use="required" />
									<xs:attribute name="growChance" type="xs:int" use="required" />
									<xs:attribute name="retailChance" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="isRetailAugmentation" type="xs:boolean" use="required" />
						<xs:attribute name="isRetailAugmentationAccessory" type="xs:boolean" use="required" />
						<xs:attribute name="baseStatChance" type="xs:int" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="forbidden" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="list" use="required" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="gemStones" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="grade" type="xs:int" use="required" />
									<xs:attribute name="gemId" type="xs:int" use="required" />
									<xs:attribute name="count" type="xs:int" use="required" />
									<xs:attribute name="accessoryCount" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" use="required" type="xs:int" use="required" />
						<xs:attribute name="grade" use="required" type="xs:int" use="required" />
						<xs:attribute name="level" use="required" type="xs:int" use="required" />
						<xs:attribute name="minLvl" use="required" type="xs:int" use="required" />
						<xs:attribute name="isWeaponAugment" type="xs:boolean" use="required" />
						<xs:attribute name="isArmorAugment" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/skills/augmentation/lifestone_map.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/lifestone_map.xsd">
	<!-- Custom Settings -->
	<configs>
		<set name="allowAugmentationPvpItems" value="false" /> <!-- Allows Augmentation of PvP items -->
		<set name="allowDropAugmentationItems" value="false" /> <!-- Allows Drop of Augmentation items -->
		<set name="allowTradeAugmentationItems" value="false" /> <!-- Allows Trade of Augmentation items -->
		<set name="allowSellAugmentationItems" value="false" /> <!-- Allows Sell of Augmentation items -->
		<set name="allowAugmentationAllItemsGrade" value="false" /> <!-- Allows Augmentation all item Grades -->
		<set name="allowArmorAugmentation" value="false" /> <!-- Custom parameter for which need to fill data in armor_augmentation.xml -->
	</configs>

	<!-- 0[No Grade] 1[Mid Grade] 2[High Grade] 3[Top Grade] 4[Acc Grade] -->
	<lifeStones isRetailAugmentation="true" isRetailAugmentationAccessory="true" baseStatChance="1">
		<grade id="0" skillChance="15" growChance="0" retailChance="55,35,7,3" />
		<grade id="1" skillChance="30" growChance="40" retailChance="55,35,7,3" />
		<grade id="2" skillChance="45" growChance="70" retailChance="55,35,7,3" />
		<grade id="3" skillChance="60" growChance="100" retailChance="55,35,7,3" />
		<grade id="4" skillChance="0" growChance="0" retailChance="55,35,7,3" />
	</lifeStones>

	<!-- Not valid items for Augmentation -->
	<forbidden list="6656,6657,6658,6659,6660,6661,6662,8191,10170,10314,13740,13741,13742,13743,13744,13745,13746,13747,13748,14592,14593,14594,14595,14596,14597,14598,14599,14600,14664,14665,14666,14667,14668,14669,14670,14671,14672,14801,14802,14803,14804,14805,14806,14807,14808,14809,15282,15283,15284,15285,15286,15287,15288,15289,15290,15291,15292,15293,15294,15295,15296,15297,15298,15299,16025,16026,21712,22173,22174,22175" />

 	<!-- Gem Stone Settings by Items Grade -->
	<gemStones>
		<item grade="2" gemId="2130" count="20" accessoryCount="200" />  <!-- C Grade Items -->
		<item grade="3" gemId="2130" count="30" accessoryCount="300" />  <!-- B Grade Items -->
		<item grade="4" gemId="2131" count="20" accessoryCount="200" />  <!-- A Grade Items -->
		<item grade="5" gemId="2131" count="25" accessoryCount="250" />  <!-- S Grade Items -->
		<item grade="6" gemId="2132" count="36" accessoryCount="360" />  <!-- S80 Grade Items -->
		<item grade="7" gemId="2132" count="36" accessoryCount="480" />  <!-- S84 Grade Items -->
	</gemStones>

	<!-- Life Stone List -->
	<item id="8723" grade="0" level="0" minLvl="46" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8724" grade="0" level="1" minLvl="49" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8725" grade="0" level="2" minLvl="52" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8726" grade="0" level="3" minLvl="55" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8727" grade="0" level="4" minLvl="58" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8728" grade="0" level="5" minLvl="61" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8729" grade="0" level="6" minLvl="64" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8730" grade="0" level="7" minLvl="67" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8731" grade="0" level="8" minLvl="70" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8732" grade="0" level="9" minLvl="76" isWeaponAugment="true" isArmorAugment="false" />

	<item id="8733" grade="1" level="0" minLvl="46" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8734" grade="1" level="1" minLvl="49" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8735" grade="1" level="2" minLvl="52" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8736" grade="1" level="3" minLvl="55" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8737" grade="1" level="4" minLvl="58" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8738" grade="1" level="5" minLvl="61" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8739" grade="1" level="6" minLvl="64" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8740" grade="1" level="7" minLvl="67" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8741" grade="1" level="8" minLvl="70" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8742" grade="1" level="9" minLvl="76" isWeaponAugment="true" isArmorAugment="false" />
		
	<item id="8743" grade="2" level="0" minLvl="46" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8744" grade="2" level="1" minLvl="49" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8745" grade="2" level="2" minLvl="52" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8746" grade="2" level="3" minLvl="55" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8747" grade="2" level="4" minLvl="58" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8748" grade="2" level="5" minLvl="61" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8749" grade="2" level="6" minLvl="64" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8750" grade="2" level="7" minLvl="67" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8751" grade="2" level="8" minLvl="70" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8752" grade="2" level="9" minLvl="76" isWeaponAugment="true" isArmorAugment="false" />
		
	<item id="8753" grade="3" level="0" minLvl="46" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8754" grade="3" level="1" minLvl="49" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8755" grade="3" level="2" minLvl="52" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8756" grade="3" level="3" minLvl="55" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8757" grade="3" level="4" minLvl="58" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8758" grade="3" level="5" minLvl="61" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8759" grade="3" level="6" minLvl="64" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8760" grade="3" level="7" minLvl="67" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8761" grade="3" level="8" minLvl="70" isWeaponAugment="true" isArmorAugment="false" />
	<item id="8762" grade="3" level="9" minLvl="76" isWeaponAugment="true" isArmorAugment="false" />
		
	<item id="9573" grade="0" level="10" minLvl="80" isWeaponAugment="true" isArmorAugment="false" />
	<item id="9574" grade="1" level="10" minLvl="80" isWeaponAugment="true" isArmorAugment="false" />
	<item id="9575" grade="2" level="10" minLvl="80" isWeaponAugment="true" isArmorAugment="false" />
	<item id="9576" grade="3" level="10" minLvl="80" isWeaponAugment="true" isArmorAugment="false" />
		
	<item id="10483" grade="0" level="11" minLvl="82" isWeaponAugment="true" isArmorAugment="false" />
	<item id="10484" grade="1" level="11" minLvl="82" isWeaponAugment="true" isArmorAugment="false" />
	<item id="10485" grade="2" level="11" minLvl="82" isWeaponAugment="true" isArmorAugment="false" />
	<item id="10486" grade="3" level="11" minLvl="82" isWeaponAugment="true" isArmorAugment="false" />
		
	<item id="12754" grade="4" level="0" minLvl="46" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12755" grade="4" level="1" minLvl="49" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12756" grade="4" level="2" minLvl="52" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12757" grade="4" level="3" minLvl="55" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12758" grade="4" level="4" minLvl="58" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12759" grade="4" level="5" minLvl="61" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12760" grade="4" level="6" minLvl="64" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12761" grade="4" level="7" minLvl="67" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12762" grade="4" level="8" minLvl="70" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12763" grade="4" level="9" minLvl="76" isWeaponAugment="false" isArmorAugment="true" />
		
	<item id="12821" grade="4" level="10" minLvl="80" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12822" grade="4" level="11" minLvl="82" isWeaponAugment="false" isArmorAugment="true" />
		
	<item id="12840" grade="4" level="0" minLvl="46" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12841" grade="4" level="1" minLvl="49" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12842" grade="4" level="2" minLvl="52" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12843" grade="4" level="3" minLvl="55" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12844" grade="4" level="4" minLvl="58" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12845" grade="4" level="5" minLvl="61" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12846" grade="4" level="6" minLvl="64" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12847" grade="4" level="7" minLvl="67" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12848" grade="4" level="8" minLvl="70" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12849" grade="4" level="9" minLvl="76" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12850" grade="4" level="10" minLvl="80" isWeaponAugment="false" isArmorAugment="true" />
	<item id="12851" grade="4" level="11" minLvl="82" isWeaponAugment="false" isArmorAugment="true" />
		
	<item id="14008" grade="4" level="12" minLvl="84" isWeaponAugment="false" isArmorAugment="true" />
		
	<item id="14166" grade="0" level="12" minLvl="84" isWeaponAugment="true" isArmorAugment="false" />
	<item id="14167" grade="1" level="12" minLvl="84" isWeaponAugment="true" isArmorAugment="false" />
