=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/sieges.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="castle" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="set" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="value" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="flameTowers" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="loc" type="xs:string" use="required" />
												<xs:attribute name="hp" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="controlTowers" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="loc" type="xs:string" use="required" />
												<xs:attribute name="hp" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="params" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="pvp" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="count" type="xs:decimal" use="required" />
												<xs:attribute name="chance" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="allowReward" type="xs:boolean" />
									<xs:attribute name="allowForParty" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="capture" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="count" type="xs:decimal" use="required" />
												<xs:attribute name="chance" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="allowReward" type="xs:boolean" use="required" />
									<xs:attribute name="onlyForLeader" type="xs:boolean" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="defence" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="count" type="xs:decimal" use="required" />
												<xs:attribute name="chance" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="allowReward" type="xs:boolean" use="required" />
									<xs:attribute name="onlyForLeader" type="xs:boolean" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" use="required" />
						<xs:attribute name="nameEn" type="xs:string" />
						<xs:attribute name="nameRu" type="xs:string" />
						<xs:attribute name="enableSiege" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/sieges/[2] Dion Castle.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/sieges.xsd">
	<castle id="2" nameEn="Dion" nameRu="Дион" enableSiege="true">
		<set name="siegeDate" value="0 20 * * 7" /> 		<!--Siege date-->
		<set name="siegeTime" value="120" />			<!--Siege time-->
		<set name="siegeCloseChangeData" value="1440" />	<!--Time in minutes before siege change date will close-->
		<set name="siegeCloseRegistration" value="720" />	<!--Time in minutes before siege start registration will close-->
		<set name="maxFlags" value="1" />			<!--Attackers flags limit-->
		<set name="siegeClanLevel" value="5" />			<!--Attackers minimum clan level-->
		<set name="attackerClans" value="500" />		<!--Attacker clans limit-->
		<set name="defenderClans" value="500" />		<!--Defender clans limit-->
		<set name="siegeLimitPlayers" value="0" />		<!--Check siege players by HWID or IP by config-->
		<set name="attackSameSiegeSide" value="true" />		<!--Allow attack other clans participating in attack or defence castle-->
		<set name="mercenariesLimit" value="150" />		<!--Mercenaries limit for summon-->
		<set name="correctSiegeHoursTime" value="16,20" />	<!--Сorrect siege time for castle lord-->
		<flameTowers> <!--Flame towers spawn-->
			<npc id="13004" loc="22114 162159 -2754 0" hp="10000" />
			<npc id="13004" loc="23289 161596 -2578 0" hp="10000" />
		</flameTowers>
		<controlTowers> <!--Control towers spawn-->
			<npc id="13002" loc="22285 156939 -2571 0" hp="10000" />
			<npc id="13002" loc="22008 162652 -2572 0" hp="10000" />
			<npc id="13002" loc="22073 161153 -2537 0" hp="10000" />
		</controlTowers>
		<params> <!--Price for castle functions-->
			<!--Teleport functions-->
			<set name="teleportFunctionTime" value="7" /> <!--Prices per days-->
			<set name="teleportPriceLvl1" value="7000" />
			<set name="teleportPriceLvl2" value="14000" />
			<!--Buff functions-->
			<set name="supportFunctionTime" value="1" /> <!--Prices per days-->
			<set name="supportPriceLvl1" value="7000" />
			<set name="supportPriceLvl2" value="21000" />
			<set name="supportPriceLvl3" value="37000" />
			<set name="supportPriceLvl4" value="52000" />
			<!--Mp Regen functions-->
			<set name="mpRegenFunctionTime" value="1" /> <!--Prices per days-->
			<set name="mpRegenPriceLvl1" value="2000" />
			<set name="mpRegenPriceLvl2" value="6500" />
			<set name="mpRegenPriceLvl3" value="13750" />
			<set name="mpRegenPriceLvl4" value="20000" />
			<!--Hp Regen functions-->
			<set name="hpRegenFunctionTime" value="1" /> <!--Prices per days-->
			<set name="hpRegenPriceLvl1" value="1000" />
			<set name="hpRegenPriceLvl2" value="1500" />
			<set name="hpRegenPriceLvl3" value="2250" />
			<set name="hpRegenPriceLvl4" value="3270" />
			<set name="hpRegenPriceLvl5" value="5166" />
			<!--Exp Regen functions-->
			<set name="expRegenFunctionTime" value="1" /> <!--Prices per days-->
			<set name="expRegenPriceLvl1" value="9000" />
			<set name="expRegenPriceLvl2" value="15000" />
			<set name="expRegenPriceLvl3" value="21000" />
			<set name="expRegenPriceLvl4" value="30000" />
		</params>
		<pvp allowReward="false" allowForParty="false"> <!--Custom reward for kill players at siege-->
			<item id="57" count="10000" chance="100" />
			<item id="4037" count="5" chance="50" />
		</pvp>
		<capture allowReward="true" onlyForLeader="true"> <!--Reward for capture castle-->
			<item id="9911" count="1" chance="100" /> <!--Blood Alliance-->
		</capture>
		<defence allowReward="true" onlyForLeader="true"> <!--Reward for defence castle-->
			<item id="9911" count="1" chance="100" /> <!--Blood Alliance-->
		</defence>
	</castle>
</list>
