=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/statLimit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="general" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="player" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="class" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="unbounded">
													<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" />
															<xs:attribute name="value" type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="summon" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="olympiad" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="player" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="class" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="unbounded">
													<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" />
															<xs:attribute name="value" type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="summon" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/chars/statLimit.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/statLimit.xsd">
	<general>
		<player>
			<class id="-1"> <!-- for all classes -->
				<set name="MOVE_SPEED" value="300" />
				<set name="CRITICAL_RATE" value="500" />
				<set name="MCRITICAL_RATE" value="20" />
				<set name="POWER_ATTACK_SPEED" value="1500" />
				<set name="MAGIC_ATTACK_SPEED" value="1999" />
				<set name="EVASION_RATE" value="250" />
				<set name="CRITICAL_DAMAGE" value="5" />
			</class>
		</player>		
		<summon>
			<set name="MOVE_SPEED" value="300" />
			<set name="CRITICAL_RATE" value="500" />
			<set name="MCRITICAL_RATE" value="20" />
			<set name="POWER_ATTACK_SPEED" value="1500" />
			<set name="MAGIC_ATTACK_SPEED" value="1999" />
			<set name="EVASION_RATE" value="250" />
			<set name="CRITICAL_DAMAGE" value="5" />
		</summon>
	</general>
	<olympiad>
		<player>
			<class id="-1"> <!-- for all classes -->
				<set name="MOVE_SPEED" value="300" />
				<set name="CRITICAL_RATE" value="500" />
				<set name="MCRITICAL_RATE" value="20" />
				<set name="POWER_ATTACK_SPEED" value="1500" />
				<set name="MAGIC_ATTACK_SPEED" value="1999" />
				<set name="EVASION_RATE" value="250" />
				<set name="CRITICAL_DAMAGE" value="5" />
			</class>
		</player>		
		<summon>
			<set name="MOVE_SPEED" value="300" />
			<set name="CRITICAL_RATE" value="500" />
			<set name="MCRITICAL_RATE" value="20" />
			<set name="POWER_ATTACK_SPEED" value="1500" />
			<set name="MAGIC_ATTACK_SPEED" value="1999" />
			<set name="EVASION_RATE" value="250" />
			<set name="CRITICAL_DAMAGE" value="5" />
		</summon>
	</olympiad>
</list>
