=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/teleports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="teleport" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="loc" type="xs:string" use="required" />
						<xs:attribute name="price" type="xs:long" />
						<xs:attribute name="noobless" type="xs:boolean" />
						<xs:attribute name="itemId" type="xs:integer" />
						<xs:attribute name="minLevel" type="xs:integer" />
						<xs:attribute name="maxLevel" type="xs:integer" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/npcs/teleports.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/teleports.xsd">
	<teleport id="1" loc="-12787 122779 -3112" price="10000" itemId="57" />
	<teleport id="2" loc="-12787 122779 -3112" price="9200" itemId="57" />
	<teleport id="3" loc="46951 51550 -2976" price="9200" itemId="57" />
	<teleport id="4" loc="9709 15566 -4568" price="10000" itemId="57" />
	<teleport id="5" loc="-80684 149770 -3040" price="7300" itemId="57" />
	<teleport id="6" loc="15472 142880 -2688" price="3400" itemId="57" />
	<teleport id="7" loc="-45158 -112583 -240" price="26000" itemId="57" />
	<teleport id="8" loc="115120 -178224 -880" price="38000" itemId="57" />
	<teleport id="9" loc="-84141 244623 -3728" price="9400" itemId="57" />
	<teleport id="10" loc="46951 51550 -2976" price="16000" itemId="57" />
	<teleport id="11" loc="9709 15566 -4568" price="16000" itemId="57" />
	<teleport id="12" loc="-12787 122779 -3112" price="7300" itemId="57" />
	<teleport id="13" loc="-16526 208032 -3664" price="3400" itemId="57" />
	<teleport id="15" loc="-80684 149770 -3040" price="18000" itemId="57" />
	<teleport id="16" loc="-12787 122779 -3112" price="32000" itemId="57" />
	<teleport id="17" loc="169008 -208272 -3504" price="2400" itemId="57" />
	<teleport id="18" loc="-12787 122779 -3112" price="3400" itemId="57" />
	<teleport id="19" loc="83551 147945 -3400" price="6800" itemId="57" />
	<teleport id="22" loc="17253 114232 -3440" />
	<teleport id="23" loc="17776 108288 -9056" />
	<teleport id="24" loc="17781 113999 -11672" />
	<teleport id="25" loc="15472 142880 -2688" price="6800" itemId="57" />
	<teleport id="26" loc="82956 53162 -1495" price="9400" itemId="57" />
	<teleport id="28" loc="105918 109759 -3192" price="4400" itemId="57" />
	<teleport id="29" loc="-112899 234942 -3688" />
	<teleport id="30" loc="48586 248459 -6160" />
	<teleport id="31" loc="84915 15969 -4294" />
	<teleport id="32" loc="85399 16197 -3679" />
	<teleport id="33" loc="85399 16197 -2809" />
	<teleport id="34" loc="85399 16197 -2293" />
	<teleport id="35" loc="85399 16197 -1776" />
	<teleport id="36" loc="82956 53162 -1495" price="3700" itemId="57" />
	<teleport id="37" loc="116819 76994 -2714" price="6800" itemId="57" />
	<teleport id="38" loc="146331 25762 -2018" price="6200" itemId="57" />
	<teleport id="40" loc="82971 53207 -1470" price="6900" itemId="57" />
	<teleport id="41" loc="117088 76931 -2688" price="5900" itemId="57" />
	<teleport id="43" loc="82971 53207 -1488" price="4100" itemId="57" />
	<teleport id="45" loc="105918 109759 -3192" price="3400" itemId="57" />
	<teleport id="46" loc="146783 25808 -2008" price="5900" itemId="57" />
	<teleport id="47" loc="83551 147945 -3400" price="9400" itemId="57" />
	<teleport id="48" loc="85391 16228 -3672" price="3700" itemId="57" />
	<teleport id="49" loc="117088 76931 -2688" price="4100" itemId="57" />
	<teleport id="50" loc="105918 109759 -3192" price="6100" itemId="57" />
	<teleport id="51" loc="146783 25808 -2008" price="6900" itemId="57" />
	<teleport id="52" loc="83551 147945 -3400" price="4400" itemId="57" />
	<teleport id="53" loc="82971 53207 -1488" price="6100" itemId="57" />
	<teleport id="54" loc="117088 76931 -2688" price="3400" itemId="57" />
	<teleport id="55" loc="17719 115590 -6584" />
	<teleport id="56" loc="17691 111726 -6583" />
	<teleport id="57" loc="17719 115590 -6584" />
	<teleport id="58" loc="17731 119465 -9067" />
	<teleport id="59" loc="83551 147945 -3400" price="7600" itemId="57" />
	<teleport id="60" loc="47938 186864 -3480" price="7100" itemId="57" />
	<teleport id="63" loc="83551 147942 -3400" price="6300" itemId="57" />
	<teleport id="65" loc="15472 142880 -2688" price="12000" itemId="57" />
	<teleport id="66" loc="87691 162835 -3563" price="12000" itemId="57" />
	<teleport id="67" loc="82192 226128 -3664" price="5900" itemId="57" /> 
	<teleport id="68" loc="115583 192261 -3488" price="2100" itemId="57" />
	<teleport id="70" loc="111455 219400 -3544" price="7600" itemId="57" />
	<teleport id="76" loc="146440 46723 -3432" price="2000" itemId="57" />
	<teleport id="81" loc="155310 -16339 -3320" price="6800" itemId="57" />
	<teleport id="84" loc="168217 37990 -4072" price="1900" itemId="57" />
	<teleport id="85" loc="111455 219400 -3544" price="12000" itemId="57" />
	<teleport id="86" loc="47382 111278 -2104" price="1700" itemId="57" />
	<teleport id="87" loc="34475 188095 -2976" price="2900" itemId="57" />
	<teleport id="88" loc="-28327 155125 -3496" price="1400" itemId="57" />
	<teleport id="90" loc="-49853 147089 -2784" price="1200" itemId="57" />
	<teleport id="91" loc="-63736 101522 -3552" price="1400" itemId="57" />
	<teleport id="92" loc="-44763 203497 -3592" price="1800" itemId="57" />
	<teleport id="93" loc="-10983 -117484 -2464" price="960" itemId="57" />
	<teleport id="94" loc="-4190 -80040 -2696" price="2000" itemId="57" />
	<teleport id="96" loc="8652 -139941 -1144" price="1600" itemId="57" />
	<teleport id="97" loc="87252 85514 -3056" price="3900" itemId="57" />
	<teleport id="98" loc="64328 26803 -3768" price="2500" itemId="57" />
	<teleport id="99" loc="104426 33746 -3800" price="3600" itemId="57" />
	<teleport id="100" loc="124904 61992 -3920" price="1300" itemId="57" />
	<teleport id="101" loc="142065 81300 -3000" price="2000" itemId="57" />
	<teleport id="107" loc="111455 219400 -3544" price="8500" itemId="57" />
	<teleport id="108" loc="43835 -47749 -792" price="10000" itemId="57" />
	<teleport id="109" loc="125740 -40864 -3736" price="4200" itemId="57" />
	<teleport id="110" loc="146990 -67128 -3640" price="1800" itemId="57" />
	<teleport id="119" loc="148024 -55281 -2728" price="10000" itemId="57" />
	<teleport id="120" loc="83551 147945 -3400" price="59000" itemId="57" />
	<teleport id="121" loc="146783 25808 -2008" price="37000" itemId="57" />
	<teleport id="122" loc="38316 -48216 -1152" price="150" itemId="57" />
	<teleport id="123" loc="38303 -48040 896" price="150" itemId="57" />
	<teleport id="124" loc="52107 -54328 -3152" price="1200" itemId="57" />
	<teleport id="125" loc="69340 -50203 -3288" price="3000" itemId="57" />
	<teleport id="126" loc="89513 -44800 -2136" price="9100" itemId="57" />
	<teleport id="132" loc="146783 25808 -2008" price="8100" itemId="57" />
	<teleport id="134" loc="43835 -47749 -792" price="37000" itemId="57" />
	<teleport id="135" loc="148024 -55281 -2728" price="8100" itemId="57" />
	<teleport id="136" loc="47938 186864 -3480" price="5200" itemId="57" />
	<teleport id="137" loc="178591 -184615 -360" price="12000" itemId="57" />
	<teleport id="201" loc="115168 16022 -5100" price="100000" itemId="57" />
	<teleport id="202" loc="114649 18587 -3609" price="150000" itemId="57" />
	<teleport id="203" loc="117918 16039 -2127" price="200000" itemId="57" />
	<teleport id="204" loc="114622 12946 -645" price="250000" itemId="57" />
	<teleport id="205" loc="112209 16078 928" price="300000" itemId="57" />
	<teleport id="206" loc="112376 16099 1947" price="350000" itemId="57" />
	<teleport id="207" loc="114448 16175 2994" price="400000" itemId="57" />
	<teleport id="208" loc="111063 16118 3967" price="450000" itemId="57" />
	<teleport id="209" loc="117147 18415 4977" price="500000" itemId="57" />
	<teleport id="210" loc="118374 15973 5987" price="550000" itemId="57" />
	<teleport id="211" loc="112209 16078 7028" price="600000" itemId="57" />
	<teleport id="212" loc="114809 18711 7996" price="650000" itemId="57" />
	<teleport id="213" loc="115178 16989 9007" price="700000" itemId="57" />
	<teleport id="214" loc="112714 14111 10077" price="800000" itemId="57" />
	<teleport id="215" loc="113098 14532 10077" price="900000" itemId="57" />
	<teleport id="250" loc="-53174 -250275 -7911" />
	<teleport id="251" loc="42514 143917 -5385" />
	<teleport id="252" loc="46217 170290 -4983" />
	<teleport id="253" loc="45770 170299 -4985" />
	<teleport id="254" loc="-20230 -250780 -8168" />
	<teleport id="255" loc="77225 78362 -5119" />
	<teleport id="256" loc="140404 79678 -5431" />
	<teleport id="257" loc="139965 79678 -5433" />
	<teleport id="258" loc="-19500 13508 -4905" />
	<teleport id="259" loc="-19931 13502 -4905" />
	<teleport id="260" loc="12521 -248481 -9585" />
	<teleport id="261" loc="113429 84540 -6545" />
	<teleport id="262" loc="-41570 209785 -5089" />
	<teleport id="263" loc="-41567 209292 -5091" />
	<teleport id="264" loc="45251 123890 -5415" />
	<teleport id="265" loc="45250 124366 -5417" />
	<teleport id="266" loc="111273 174015 -5417" />
	<teleport id="267" loc="110818 174010 -5443" />
	<teleport id="268" loc="-21726 77385 -5177" />
	<teleport id="269" loc="-22197 77369 -5177" />
	<teleport id="270" loc="-52254 79103 -4743" />
	<teleport id="271" loc="-52716 79106 -4745" />
	<teleport id="272" loc="118308 132800 -4833" />
	<teleport id="273" loc="117793 132810 -4835" />
	<teleport id="274" loc="83000 209213 -5443" />
	<teleport id="275" loc="82608 209225 -5443" />
	<teleport id="276" loc="172251 -17605 -4903" />
	<teleport id="277" loc="171902 -17595 -4905" />
	<teleport id="350" loc="22967 157715 -2954" />
	<teleport id="351" loc="22090 159871 -2711" />
	<teleport id="352" loc="22448 155798 -2958" />
	<teleport id="353" loc="22592 161530 -2775" />
	<teleport id="354" loc="22967 157715 -2954" />
	<teleport id="355" loc="22448 155798 -2958" />
	<teleport id="356" loc="22592 161530 -2775" />
	<teleport id="357" loc="22090 159871 -2711" />
	<teleport id="358" loc="22448 155798 -2958" />
	<teleport id="359" loc="22592 161530 -2775" />
	<teleport id="360" loc="22967 157715 -2954" />
	<teleport id="361" loc="22090 159871 -2711" />
	<teleport id="362" loc="113892 144175 -2714" />
	<teleport id="363" loc="115984 145073 -2584" />
	<teleport id="364" loc="112016 144682 -2833" />
	<teleport id="365" loc="117619 144564 -2648" />
	<teleport id="366" loc="113892 144175 -2714" />
	<teleport id="367" loc="112016 144682 -2833" />
	<teleport id="368" loc="117619 144564 -2648" />
