=== ttlyceo/JSOFT_SP-main/dist/game/data/xsd/worldEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="event" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="time" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="startPattern" type="xs:string" />
									<xs:attribute name="stopPattern" type="xs:string" />
									<xs:attribute name="isNonStop" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="spawnlist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger" />
												<xs:attribute name="x" type="xs:integer" />
												<xs:attribute name="y" type="xs:integer" />
												<xs:attribute name="z" type="xs:integer" />
												<xs:attribute name="heading" type="xs:integer" />
											</xs:complexType>
										</xs:element>
										<xs:element name="location" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="x" type="xs:integer" />
												<xs:attribute name="y" type="xs:integer" />
												<xs:attribute name="z" type="xs:integer" />
												<xs:attribute name="h" type="xs:integer" />
											</xs:complexType>
										</xs:element>
										<xs:element name="territory" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="unbounded">
													<xs:element name="add" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="x" type="xs:integer" />
															<xs:attribute name="y" type="xs:integer" />
															<xs:attribute name="zmin" type="xs:integer" />
															<xs:attribute name="zmax" type="xs:integer" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="droplist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
												<xs:attribute name="min" type="xs:integer" />
												<xs:attribute name="max" type="xs:integer" />
												<xs:attribute name="chance" type="xs:decimal" />
												<xs:attribute name="minLvl" type="xs:integer" />
												<xs:attribute name="maxLvl" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="add_parameters" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewardlist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="variant" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="unbounded">
													<xs:element name="reward" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:integer" />
															<xs:attribute name="min" type="xs:integer" />
															<xs:attribute name="max" type="xs:integer" />
															<xs:attribute name="chance" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
													<xs:element name="request" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:integer" />
															<xs:attribute name="min" type="xs:integer" />
															<xs:attribute name="max" type="xs:integer" />
														</xs:complexType>
													</xs:element>
													<xs:element name="random" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence minOccurs="1" maxOccurs="unbounded">
																<xs:element name="reward" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:integer" />
																		<xs:attribute name="min" type="xs:integer" />
																		<xs:attribute name="max" type="xs:integer" />
																		<xs:attribute name="chance" type="xs:decimal" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
						<xs:attribute name="nameEn" type="xs:string" />
						<xs:attribute name="nameRu" type="xs:string" />
						<xs:attribute name="activate" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/worldEvents/[15] Race.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/worldEvent.xsd">
	<event id="15" nameRu="Гонка" nameEn="Race" activate="false">
		<time startPattern="0 21 * * 6" stopPattern="10 21 * * 6" isNonStop="false" />
		<spawnlist>
			<!-- Event Manager -->
			<npc id="900103" x="18429" y="145861" z="-3090" heading="0" />
			<!-- Finish Locations -->
			<location name="Heretic catacomb enterance" x="39177" y="144345" z="-3650" h="0" />
			<location name="Dion castle bridge" x="22294" y="155892" z="-2950" h="0" />
			<location name="Floran village enterance" x="16537" y="169937" z="-3500" h="0" />
			<location name="Floran fort gate" x="7644" y="150898" z="-2890" h="0" />
		</spawnlist>
		<add_parameters>
			<set name="regTime" value="5" />
			<set name="transformSkill" value="6201" />
		</add_parameters>
		<rewardlist>
			<variant id="1"><!-- Random one Item -->
				<!-- Reward Items -->
				<random>
					<reward id="6622" min="2" />
					<reward id="9625" min="2" />
					<reward id="9626" min="2" />
					<reward id="9627" min="2" />
					<reward id="9546" min="5" />
					<reward id="9547" min="5" />
					<reward id="9548" min="5" />
					<reward id="9549" min="5" />
					<reward id="9550" min="5" />
					<reward id="9551" min="5" />
					<reward id="9574" min="3" />
					<reward id="9575" min="2" />
					<reward id="9576" min="1" />
					<reward id="20034" min="1" />
				</random>
			</variant>
		</rewardlist>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/worldEvents/[14] Rabbits.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/worldEvent.xsd">
	<event id="14" nameRu="Кролики" nameEn="Rabbits" activate="false">
		<time startPattern="0 20 * * 7" stopPattern="2 20 * * 7" isNonStop="false" />
		<spawnlist>
			<!-- Event Manager -->
			<location name="Fantasy Isle" x="-59227" y="-56939" z="-2032" h="64106" />
			<!-- Mobs Territory -->
			<territory name="Fantasy Isle">
				<add x="-58712" y="-55880" zmin="-2040" zmax="-2000" />
				<add x="-60744" y="-55896" zmin="-2040" zmax="-2000" />
				<add x="-60744" y="-57912" zmin="-2040" zmax="-2000" />
				<add x="-58712" y="-57912" zmin="-2040" zmax="-2000" />
			</territory>
		</spawnlist>
		<droplist>
			<item id="1540" min="10" max="15" chance="80" /> <!-- Quick Healing Potion -->
			<item id="1538" min="5" max="10" chance="60" /> <!-- Blessed Scroll of Escape -->
			<item id="3936" min="5" max="10" chance="40" /> <!-- Blessed Scroll of Resurrection -->
			<item id="6387" min="5" max="10" chance="25" /> <!-- Blessed Scroll of Resurrection for Pets -->
			<item id="22025" min="5" max="10" chance="10" /> <!-- Greater Healing Potion -->
			<item id="6622" min="1" max="1" chance="5" /> <!-- Giant's Codex -->
			<item id="20034" min="1" max="1" chance="5" /> <!-- Revita-Pop -->
			<item id="20004" min="1" max="1" chance="5" /> <!-- Vitality Ginseng -->
		</droplist>
		<add_parameters>
			<set name="canUseMagic" value="false" />
			<set name="totalAmount" value="100" />
		</add_parameters>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/worldEvents/[08] Grand Wedding.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/worldEvent.xsd">
	<event id="8" nameRu="Свадьба" nameEn="Grand Wedding" activate="false">
		<time startPattern="30 9 1 * *" stopPattern="30 9 30 * *" isNonStop="false" />
		<spawnlist>
			<!-- Event Manager -->
			<npc id="102510" x="146364" y="27322" z="-2205" heading="62980" />
			<npc id="102510" x="147982" y="-56568" z="-2781" heading="20998" />
			<npc id="102510" x="83486" y="149328" z="-3405" heading="47599" />
		</spawnlist>
		<rewardlist>
			<variant id="1">
				<!-- Reward Items -->
				<reward id="4037" min="10" />
			</variant>
		</rewardlist>
	</event>
</list>

=== ttlyceo/JSOFT_SP-main/dist/game/data/stats/events/worldEvents/[18] Lovers Jubilee.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/worldEvent.xsd">
	<event id="18" nameRu="Юбилей Влюбленных" nameEn="Lovers Jubilee" activate="false">
        	<time startPattern="0 18 16 2 *" stopPattern="0 18 23 2 *" isNonStop="false" />
       	 	<spawnlist>
            		<!-- Rosalia -->
            		<npc id="4305" x="87792" y="-142240" z="-1343" heading="44000" />
            		<npc id="4305" x="87616" y="-140688" z="-1542" heading="16500" />
            		<npc id="4305" x="16622" y="142834" z="-2708" heading="16384" />
            		<npc id="4305" x="18559" y="145920" z="-3075" heading="49152" />
            		<npc id="4305" x="82160" y="148544" z="-3469" heading="0" />
            		<npc id="4305" x="82543" y="149728" z="-3471" heading="49151" />
            		<npc id="4305" x="82173" y="146432" z="-3535" heading="16384" />
            		<npc id="4305" x="-81024" y="149848" z="-3046" heading="0" />
            		<npc id="4305" x="-83169" y="151208" z="-3131" heading="0" />
            		<npc id="4305" x="-13726" y="122416" z="-2990" heading="49151" />
            		<npc id="4305" x="-14192" y="124319" z="-3119" heading="32768" />
            		<npc id="4305" x="-84600" y="244586" z="-3731" heading="57343" />
            		<npc id="4305" x="-84240" y="243255" z="-3731" heading="16000" />
            		<npc id="4305" x="46767" y="51007" z="-2998" heading="8192" />
            		<npc id="4305" x="46070" y="48610" z="-3062" heading="23000" />
            		<npc id="4305" x="9912" y="15307" z="-4577" heading="14000" />
            		<npc id="4305" x="11491" y="17663" z="-4587" heading="46999" />
            		<npc id="4305" x="80304" y="56527" z="-1562" heading="49151" />
            		<npc id="4305" x="82160" y="53255" z="-1498" heading="16384" />
            		<npc id="4305" x="148550" y="26781" z="-2208" heading="32768" />
            		<npc id="4305" x="146224" y="25846" z="-2016" heading="0" />
            		<npc id="4305" x="117354" y="76690" z="-2695" heading="45000" />
            		<npc id="4305" x="116210" y="77084" z="-2728" heading="4096" />
            		<npc id="4305" x="-119420" y="44881" z="368" heading="25500" />
            		<npc id="4305" x="-117265" y="46367" z="367" heading="16384" />
            		<npc id="4305" x="111871" y="219198" z="-3545" heading="49151" />
            		<npc id="4305" x="108303" y="221815" z="-3600" heading="0" />
            		<npc id="4305" x="-44687" y="-113169" z="-241" heading="16384" />
            		<npc id="4305" x="115067" y="-177823" z="-882" heading="0" />
            		<npc id="4305" x="117047" y="-182670" z="-1530" heading="24576" />
            		<npc id="4305" x="149022" y="-56015" z="-2783" heading="45055" />
            		<npc id="4305" x="147471" y="-56834" z="-2782" heading="0" />
            		<npc id="4305" x="42896" y="-48479" z="-798" heading="16384" />
            		<npc id="4305" x="44694" y="-50684" z="-799" heading="22000" />
        	</spawnlist>
        	<droplist>
            		<item id="20903" min="1" max="1" chance="25" minLvl="1" maxLvl="85" />
            		<item id="20904" min="1" max="1" chance="10" minLvl="1" maxLvl="85" />
            		<item id="20914" min="1" max="1" chance="5" minLvl="1" maxLvl="85" />
        	</droplist>
        	<rewardlist>
            		<variant id="2">
                		<!-- Request Items -->
                		<request id="57" min="500" />
                		<!-- Reward Items -->
                		<reward id="20905" min="1" />
            		</variant>
            		<variant id="3">
                		<!-- Request Items -->
                		<request id="57" min="500" />
                		<!-- Reward Items -->
                		<reward id="20906" min="1" />
            		</variant>
            		<variant id="4">
                		<!-- Request Items -->
                		<request id="57" min="500" />
                		<!-- Reward Items -->
                		<reward id="20907" min="1" />
            		</variant>
            		<variant id="5">
                		<!-- Request Items -->
                		<request id="57" min="5000" />
                		<!-- Reward Items -->
                		<reward id="20905" min="10" />
            		</variant>
            		<variant id="6">
                		<!-- Request Items -->
                		<request id="57" min="5000" />
                		<!-- Reward Items -->
                		<reward id="20906" min="10" />
            		</variant>
            		<variant id="7">
                		<!-- Request Items -->
                		<request id="57" min="5000" />
                		<!-- Reward Items -->
                		<reward id="20907" min="10" />
            		</variant>
            		<variant id="9">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20908" min="1" />
            		</variant>
            		<variant id="10">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20909" min="1" />
            		</variant>
            		<variant id="11">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20910" min="1" />
            		</variant>
            		<variant id="12">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20911" min="1" />
            		</variant>
            		<variant id="13">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20912" min="1" />
            		</variant>
            		<variant id="14">
                		<!-- Reward Items -->
                		<reward id="20921" min="1" />
                		<reward id="20913" min="1" />
            		</variant>
            		<variant id="15">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20915" min="1" />
            		</variant>
            		<variant id="16">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20916" min="1" />
            		</variant>
            		<variant id="17">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20917" min="1" />
            		</variant>
            		<variant id="18">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20918" min="1" />
            		</variant>
            		<variant id="19">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20919" min="1" />
            		</variant>
            		<variant id="20">
                		<!-- Reward Items -->
                		<reward id="20914" min="1" />
                		<reward id="20920" min="1" />
            		</variant>
        	</rewardlist>
    	</event>
</list>
